### ISSUE TITLE
Registering commands; Check command bot name using regexp

### ISSUE THREAD

**Issue by IgorPr** [westacks/telebot#10]
Could you write an example like "Creating command" for "Registering commands", please? I don't understand where I should write this code.

<img width="1126" alt="Screenshot 2021-02-12 at 16 36 09" src="https://user-images.githubusercontent.com/3995869/107782088-5160a980-6d51-11eb-9025-4ded7a26b322.png">

**Comment by PunyFlash** [comment]
Hello. [`CommandHandler`](https://github.com/westacks/telebot/blob/d0b7e059be7b06500ec693c1f82fee93cbc45f8c/src/Handlers/CommandHandler.php#L12) class is extension of UpdateHandler class. So you may register it like regular `UpdateHandler`:

https://westacks.github.io/telebot/#/updates?id=creating-handlers  (check "Registering Handlers" tab);
https://westacks.github.io/telebot/#/laravel?id=bot-commands (check "Commands Config" tab);

I agree that that's not obvious from the docs. I'll try to describe this part more properly.

**Comment by IgorPr** [comment]
If I understand correctly, I should create StartCommand class
<img width="679" alt="Screenshot 2021-02-13 at 14 59 19" src="https://user-images.githubusercontent.com/3995869/107850687-e70d3f00-6e0c-11eb-9283-dc4c647330bf.png">

After that I should register this class (telebot.php)
<img width="1123" alt="Screenshot 2021-02-13 at 14 59 48" src="https://user-images.githubusercontent.com/3995869/107850714-1623b080-6e0d-11eb-8b35-bea5c21dfbe8.png">

Is it right?

**Comment by PunyFlash** [comment]
Yes, this seems legit. If your have your token configured and the bot is working now, on `/start` command he should answer you `Hello, World!`. You may host bot locally without webhook using [long-polling](https://westacks.github.io/telebot/#/laravel?id=long-polling).

**Comment by IgorPr** [comment]
Unfortunately, this case does't work for me. 
I created webhook before command. When I write /start in a chat, telegram send request to webhook endpoint :(

I guess I messed up something in the settings

**Comment by PunyFlash** [comment]
You actually not forced to setup your own webhook URL. Library provides it's [own route](https://github.com/westacks/telebot/blob/d0b7e059be7b06500ec693c1f82fee93cbc45f8c/src/Laravel/TeleBotServiceProvider.php#L18) for that. All you need is just setup correct `APP_URL` and run `php artisan telebot:webhook --setup` on your production - you want to uncomment `bot.webhook.url` only if you want to write something additional for your webhook.

I can't tell what is your problem now. Please provide laravel logs and output of `php artisan telebot:webhook --info`

**Comment by IgorPr** [comment]
Oh, I had change /telebot/webhook/bot/
php artisan telebot:webhook --setup
php artisan telebot:webhook --info
************************
*     Webhook Info     *
************************

  A cell must be a TableCell, a scalar or an object implementing "__toString()", "array" given.

Also I have response from telegram API
`{
ok: true,
result: {
url: "https://df09e326d0cf.ngrok.io/telebot/webhook/bot/0000000000:XXXXXXXXXX",
has_custom_certificate: false,
pending_update_count: 0,
max_connections: 40,
ip_address: "3.14.182.203",
allowed_updates: [
"message",
"edited_channel_post",
"callback_query"
]
}
}`

 php artisan telebot:commands --info
************************
*     Bot Commands     *
************************

+---------+----------------------------------------------+
| Bot: bot                                               |
+---------+----------------------------------------------+
| Command | Description                                  |
+---------+----------------------------------------------+
| /start  | Send "/start" or "/s" to get "Hello, World!" |
| /s      | Send "/start" or "/s" to get "Hello, World!" |
+---------+----------------------------------------------+

**Comment by IgorPr** [comment]
I found issue.
Take a look on the method, I added comments
`public static function trigger(Update $update)
    {
        if (!isset($update->message) || !isset($update->message->entities)) {
            return false;
        }

        // The $entity contains {"offset":0,"length":23,"type":"bot_command"}
        foreach ($update->message->entities as $entity) {
            if ('bot_command' != $entity->type) {
                continue;
            }
            
            /** The $update->message->text contains /start@SimpleAaaaaaaBot
             *.   The static::$aliases contains [/start, /s]
             **/

            //In this case substr function should get /start, but it get whole string.
            $command = substr($update->message->text, $entity->offset, $entity->length);
            if (in_array($command, static::$aliases)) {

                return true;
            }
        }

        return false;
    }`

**Comment by PunyFlash** [comment]
Oh, this is actualy a bug as library is not checking for bot name on command handling. There should be a regexp to handle it

**Comment by PunyFlash** [comment]
For now please override a `trigger` function on child classes for a command by yourself. I'll fix this after weekends or merge incoming sollutions.
