### ISSUE TITLE
Handle Throwable

### ISSUE THREAD

**Issue by bosskokoss** [westacks/telebot#19]
Очень нубский вопрос.
Можно ли как то перехватить TelegramRequestException для всех уже существующих хендлеров. 

Дописывать в каждом хендлере try..catch совсем не комильфо.
Как лучше перегрузить или переопределить и какой именно класс

**Comment by bosskokoss** [comment]
С меня небольшой донейшн за подсказанное решение. Телега задрачивает после блокировки бота каким то юзиком и выполняет логику хендлеров чуть ли не 500 раз)

**Comment by bosskokoss** [comment]
А. сорян, вопрос отпал)

**Comment by bosskokoss** [comment]
не могу найти код что бы логировались эксепшены в случае если вылетают при их отключении в конфиг файле.

**Comment by PunyFlash** [comment]
Привет!
В вашем случае, удобнее всего было бы написать свой контроллер для webhook-роута. По умолчанию контроллер выглядит так: https://github.com/westacks/telebot/blob/20ae6babf7f3e0ec2093f134e341469a2cc1eb3a/src/Laravel/Controllers/WebhookController.php#L10-L20.
Вам необходимо написать свой контроллер, в котором вы обработаете ошибку вручную:

```php
try {
    TeleBot::bot($bot)->handleUpdate();
} catch (TelegramRequestException $e) {
    Log::error($e);
}
```

Что-бы задать webhook вручную, необходимо указать `webhook.url` в конфиге:
https://github.com/westacks/telebot/blob/20ae6babf7f3e0ec2093f134e341469a2cc1eb3a/src/Laravel/config/telebot.php#L34

**Comment by bosskokoss** [comment]
Отлично! Спасибо огромное. Закину донейт.
