### ISSUE TITLE
Testing support

### ISSUE THREAD

**Issue by punyflash** [westacks/telebot#28]
### Discussed in https://github.com/westacks/telebot/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **roelofr** September 21, 2021</sup>
Hey there,

I just discovered this package via my GitHub homepage (I didn't know it did that).

It looks great, but I'm seeing no docs on testing <ins>from an end-user perspective</ins> (which is something a *lot* of Telegram bot packages don't have).

What would be the best way to test this, I'd be glad to help.</div>

**Comment by newtmex** [comment]
I think the way to test this would be to have a complete end-to-end testing setup.

I have had this thought before, but in a different form.

I write unit and feature tests, I would love to fake the sending of messages with telebot, just the way we can fake sending mails or dispatching of events.

**Comment by punyflash** [comment]
> I think the way to test this would be to have a complete end-to-end testing setup.
> 
> I have had this thought before, but in a different form.
> 
> I write unit and feature tests, I would love to fake the sending of messages with telebot, just the way we can fake sending mails or dispatching of events.

Well, this is the way I'm trying to implement right now and this is not feel right so far - there is no way to check if you're giving proper request parameters and data flow is just makes no sense. I do believe that the correct way would be something like in [`telegram-test-api`](https://github.com/jehy/telegram-test-api), but this is tons of work to do - I will die trying to support this.

**Comment by lolmaster277** [comment]
У вас ошибка в документации на сайте.
```
WeStacks\TeleBot\Laravel\TeleBotServiceProvider::class,
 Вместо 

WeStacks\TeleBot\Laravel\Providers\TeleBotServiceProvider::class,
```

**Comment by punyflash** [comment]
Most methods support mocking now. Implementing whole replica of bot API is not convenient.
