### ISSUE TITLE
You should specify at least 1 bot to use BotManager

### ISSUE THREAD

**Issue by ajianaz** [westacks/telebot#29]
hey sir,
i got issue WeStacks\TeleBot\Exception\TeleBotObjectException. You should specify at least 1 bot to use BotManager.

in local run perfect. but in cloud always return like that.
thanks.

**Comment by punyflash** [comment]
Helo. I can't help you without any code. Check your configuration for any issues. You got this exception from `BotManager` constructor:

https://github.com/westacks/telebot/blob/71599c04fd0bd1c8f7424137be90ab242a000d79/src/BotManager.php#L138-L147

**Comment by ajianaz** [comment]
Thanks for answer my question.
i think this is error from my server setting.

cause in local is running well.

my bad for not checking it first.
sorry for take your time.
