### ISSUE TITLE
Auto Delete After Set Time

### ISSUE THREAD

**Issue by DavidWhicker** [westacks/telebot#30]
Would it be possible to add a delete message after say 60 seconds from being sent. I beleive the Telegram API supports this. 

Thank you

**Comment by DavidWhicker** [comment]
https://core.telegram.org/bots/api#deletemessage

**Comment by punyflash** [comment]
Well, you answered your question by yourself. It is. Best practice will be to have a queued job that you execute after 30 seconds when message was sent.
