### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by DavidWhicker** [westacks/telebot#31]
Hello

Sorry to trouble you again. 

I am trying to get callback data that orignates from a command. 

```php
$test = $this->sendMessage([
    'text' => 'testing' ,
    'reply_markup' => [
            'resize_keyboard' => true, 
                    'one_time_keyboard' => true,
                    'inline_keyboard' => [[
                        ['text' => 'summary','callback_data' => "1"],
                        ['text' => 'listvalidators','callback_data' => "2"]
                    ]]
            ] 
]);
```

Once a callback button is clicked. 

How do I go about getting that data? Sorry and thank you

**Comment by DavidWhicker** [comment]
Think Ive just sorted it. I noticed it goes to URL/telebot/webhook/bot/

I can grab the info from there. Thank you

**Comment by punyflash** [comment]
When user clicks inline button, Telegram sends [CallbackQuery](https://core.telegram.org/bots/api#callbackquery)  update. I'm not consulting how to work with Telegram's bot API. Read the docs by yourself.

**Comment by DavidWhicker** [comment]
Thank you for coming back to me. 

I didn’t mean to trouble you. I was just trying to work out how to access the callback via your plugin. I have been reading the telegram docs but obviously that doesn’t directly apply back to your plugin ( laravel ).

Thank you though.
