### ISSUE TITLE
Problem in istallation

### ISSUE THREAD

**Issue by ynaderi1959** [westacks/telebot#38]
Laravel Framework 9.0.2
PHP 8.0.6 & 
PHP 7.4.9

`composer require westacks/telebot`

Output:

  Problem 1
    - Root composer.json requires laravel/framework ^9.0, found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but the package is fixed to v8.81.0 (lock file version) by a partial update and that version does not match. Make sure yo
u list it as an argument for the update command.
  Problem 2
    - Root composer.json requires nunomaduro/collision ^6.1, found nunomaduro/collision[v6.1.0] but the package is fixed to v5.11.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an
 argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

When using `composer require westacks/telebot -W`

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^9.0, found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - Root composer.json requires nunomaduro/collision ^6.1, found nunomaduro/collision[v6.1.0] but the package is fixed to v5.11.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an
 argument for the update command.
  Problem 3
    - laravel/sanctum is locked to version v2.14.0 and an update of this package was not requested.
    - laravel/sanctum v2.14.0 requires illuminate/database ^6.9|^7.0|^8.0|^9.0 -> found illuminate/database[v6.10.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, l
ikely because it conflicts with another require.
  Problem 4
    - laravel/tinker is locked to version v2.7.0 and an update of this package was not requested.
    - laravel/tinker v2.7.0 requires illuminate/console ^6.0|^7.0|^8.0|^9.0 -> found illuminate/console[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely
 because it conflicts with another require.
  Problem 5
    - laravel/sail is locked to version v1.13.1 and an update of this package was not requested.
    - laravel/sail v1.13.1 requires illuminate/console ^8.0|^9.0 -> found illuminate/console[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by punyflash** [comment]
None of your composer errors are related to `telebot` library

**Comment by ynaderi1959** [comment]
The errors appear when I wanted to install the telebot

**Comment by punyflash** [comment]
No, the error appeared because you tried to upgrade your project to Laravel 9 without updating your dependencies. Read your problem context:
```
Root composer.json requires laravel/framework ^9.0, found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but the package is fixed to v8.81.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```
First make sure your `composer.json` and `composer.lock` are valid by themselves and then blame my library.

**Comment by ynaderi1959** [comment]
Don't take it personal.
I don't blame the library.
I wanted to install your library on a fresh Laravel project

**Comment by ynaderi1959** [comment]
Thanks for the help.
I've deleted the `vendor` and `composer.lock` and run the `composer update` command in `phpstorm`.
But when I redo all in `cmd`, the problem resolved

btw
![image](https://user-images.githubusercontent.com/75188348/154864234-7aefae68-81b7-49b1-a158-3cdd8c659fa5.png)

miss a comma after api_url
