### ISSUE TITLE
get error when use many hendlers in laravel 

### ISSUE THREAD

**Issue by DyarWeb** [westacks/telebot#48]
Laravel ERROR (local):
Value of type null is not callable {"exception":"[object] (Error(code: 0): Value of type null is not callable at /project/vendor/westacks/telebot/src/Handlers/UpdateHandler.php:89)"} []

'handlers' => [
        HomeCommands::class,
        ProjectAdminsCommands::class,
        AddNewFilm::class
]

If I use one handler (does not matter which one) it works without any problems

If I use two, it gives an error, but both of them work without any problems

If I use more than two, it gives an error and only the last two run 

i have this problem just in version ^2 of telebot

**Comment by DyarWeb** [comment]
i fix this in #49 :)

**Comment by punyflash** [comment]
Fixed in 5c5a519a965ba68bac38382df9bc67d48a6cd02a
