### ISSUE TITLE
How can I make a Menu button which opening a web app?

### ISSUE THREAD

**Issue by etal0n** [westacks/telebot#50]
I tried to do something like that, but it doesn`t work:

```
class AppCommand extends CommandHandler
{
    protected static $aliases = ['/app'];
    protected static $description = 'Run application';

    public function handle()
    {
        $webAppInfo = WebAppInfo::create([
            'url' => 'https://example.com/app',
        ]);

        $menuButtonWebApp = MenuButtonWebApp::create([
            'type' => 'web_app',
            'text' => 'App',
            'web_app' => $webAppInfo,
        ]);

        return $menuButtonWebApp;
    }
}
```
or
```
return $this->setChatMenuButton([
    'chat_id' => env('TELEGRAM_CHAT_ID'),
    'menu_button' => $menuButtonWebApp
]);
```

Laravel 9

**Comment by punyflash** [comment]
There is [Discussions](https://github.com/westacks/telebot/discussions) tab for questions. Issues are for reporting bugs and proposing new features.

I never personally worked with web apps yet, but according to the [Telegram Bot API](https://core.telegram.org/bots/api#setchatmenubutton), your code should be something like this:

```php
$this->setChatMenuButton([
    'menu_button' => [
        'type' => 'web_app',
        'text' => 'My App',
        'web_app' => [
            'url' => '<your web app url>'
        ]
    ]
]);
```

**Comment by etal0n** [comment]
> There is a [Discussions](https://github.com/westacks/telebot/discussions) tab for questions. Issues are for reporting bugs and proposing new features.

My bad.



> From my investigations, this works well.

Yes, works perfectly! Thank you very much!
