### ISSUE TITLE
Tests are failing when using handleUpdate() in loop

### ISSUE THREAD

**Issue by VampireAotD** [westacks/telebot#58]
Hello!

I was writing tests for my application, and noticed that some tests are failing if i use `$bot->handleUpdate()` in a loop. The exception message was `Not Found`, so it seems that after first iteration bot is not considered fake anymore. This only occures in loops and only if i need to send something through bot : message, photo, location, etc.

Here is an code example : 

```php
public function testIssueExample(): void
    {
        $bot = LaravelWrapper::bot()->fake(); // LaravelWrapper is a Facade for Laravel
        $bot->clearHandlers();
        $bot->addHandler(
            [
                function (TeleBot $bot, Update $update, $next) {
                    return $bot->sendMessage(
                        [
                            'chat_id' => -1,
                            'text'    => $update->message->text,
                        ]
                    );
                },
            ]
        );

        $messages = ['random', 'text'];

        foreach ($messages as $message) {
            $update   = Update::create(
                [
                    'message' => [
                        'chat' => [
                            'id' => -1,
                        ],
                        'text' => $message,
                    ],
                ]
            );
            // On second iteration will try to send message like a real bot and will fail test
            $response = $bot->handleUpdate($update);
            $this->assertEquals($response->text, $message);
        }
    }
```

If you dump bot on each iteration, you can see that on first iteration bot `fake` property will be set to `true` : 

```
WeStacks\TeleBot\TeleBot^ { 
   // ommited config and other properties
   +"fake": true
}
```

And on the second iteration and further it will be set to `null` : 

```
WeStacks\TeleBot\TeleBot^ { 
   // ommited config and other properties
   +"fake": null
}
```

So to make my tests work i need to manually call `fake()` on each iteration : 

```php
public function testIssueExample(): void
    {
        $bot = LaravelWrapper::bot()->fake(); // LaravelWrapper is a Facade for Laravel
        $bot->clearHandlers();
        $bot->addHandler(
            [
                function (TeleBot $bot, Update $update, $next) {
                    return $bot->sendMessage(
                        [
                            'chat_id' => -1,
                            'text'    => $update->message->text,
                        ]
                    );
                },
            ]
        );

        $messages = ['random', 'text'];

        foreach ($messages as $message) {
            $update   = Update::create(
                [
                    'message' => [
                        'chat' => [
                            'id' => -1,
                        ],
                        'text' => $message,
                    ],
                ]
            );
	     // Will pass
            $response = $bot->fake()->handleUpdate($update);
            $this->assertEquals($response->text, $message);
        }
    }
```

I've investigated a bit more and i think problem can be in this lines of code : https://github.com/westacks/telebot/blob/master/src/TeleBot.php#L101-L103.

Can this be fixed somehow or is it intentional behaviour?

I would also like to thank you for all your hard work with this library, it made my development so much easier and fast :heart_eyes: :heart_eyes:

**Comment by punyflash** [comment]
Hello! This issue is related to #28.
Firstly, bot testing is extremely unstable and was not officially released yet. And probably, will not and will be deleted in future versions as it is not testing telegram's logic - only mocked response, and I'm not really sure if I've finished mocks for every possible object. However, you are using `fake` toggle wrong. You should use it before using Telegram's API method, same as `async` and `exceptions`. For example, in your code you should use it like so:

```php
public function testIssueExample(): void
{
    $bot = LaravelWrapper::bot(); // LaravelWrapper is a Facade for Laravel
    $bot->clearHandlers();
    $bot->addHandler(fn (TeleBot $bot, Update $update, $next) =>
        $bot->fake()->sendMessage([
            'chat_id' => -1,
            'text'    => $update->message->text,
        ])
    );

    $messages = ['random', 'text'];

    foreach ($messages as $message) {
        $update = Update::create([
            'message' => [
                'chat' => [
                    'id' => -1,
                ],
                'text' => $message,
            ],
        ]);

        $response = $bot->fake()->handleUpdate($update);
        $this->assertEquals($response->text, $message);
    }
}
```

You getting `Not Found` error because when you calling this:

```php
$bot->sendMessage([
    'chat_id' => -1,
    'text'    => $update->message->text,
]);
```

, you sending request to Telegram's API and trying to send message to chat with id `-1` which is not exists

**Comment by VampireAotD** [comment]
Thank you very much for your reply!

So for now i came up with two options for me: refactor my handlers a bit or stick to `$bot->fake()->handleUpdate()` in loop,
will figure out which option is for me better later :)

As for tests, i don't know about coverage of all methods and even though its just mocks, i was really happy to see you added such simple and efficient way to test bots and handlers, because now it is very easy to test single and chains of handlers and their responses, and though it's up to you but i hope you won't delete it, because it is a solid base for testing that made it so much simpler than it used to be :heart_eyes:

Anyway, thank you very much for your time and help, looking forward to use new versions of this library and wish you all goods :blush:
