### ISSUE TITLE
Cannot cast value of type NULL to type string in inline_query

### ISSUE THREAD

**Issue by DyarWeb** [westacks/telebot#59]
Hello, inline_query does not work and there is an error
Cannot cast value of type NULL to type string
It says when I try to use it

**Comment by punyflash** [comment]
Your description is unclear. Please follow a [template](https://github.com/westacks/telebot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to report a bug

**Comment by DyarWeb** [comment]
1. Turn on Inline mode in BotFather
2. use Inline mode : `@bot_username some_thing`

Then you will receive the following error in log channel if you add it:
`Laravel ERROR (local):
Cannot cast value of type NULL to type string {"exception":"[object] (WeStacks\\TeleBot\\Exceptions\\TeleBotException(code: 0): Cannot cast value of type NULL to type string at /var/www/vendor/westacks/telebot/src/Helpers/Type.php:96)"} []`

**Comment by punyflash** [comment]
Inline mode works well. Issue will not be worked on.
