### ISSUE TITLE
Php8 support

### ISSUE THREAD

**Issue by 2618094** [westacks/telebot#6]
Hello!
Pls make an php8 support for this lbrary :)

**Comment by PunyFlash** [comment]
Hello!
Thanks for your request. Currently waiting for `spatie/guzzle-rate-limiter-middleware` package update for php 8 compatibility. If there no pull requests till monday, I'll rewrite middleware by myself to not relly on their package. Dedline for php 8 compatibility is December 11th. Thanks for your patience =)
