### ISSUE TITLE
[Cannot cast value of type NULL to type string error in Inline mode]

### ISSUE THREAD

**Issue by DyarWeb** [westacks/telebot#60]
**Describe the bug**
Hello, The library does not support Inline mode and I tested it with a simple bot and got
Cannot cast value of type NULL to type string error in log channel

**To Reproduce**

1.Turn on Inline mode in BotFather
2.use Inline mode : `@bot_username some_thing`

Then you will receive the following error in log channel if you add it:
`Laravel ERROR (local): Cannot cast value of type NULL to type string {"exception":"[object] (WeStacks\\TeleBot\\Exceptions\\TeleBotException(code: 0): Cannot cast value of type NULL to type string at /var/www/vendor/westacks/telebot/src/Helpers/Type.php:96)"} []`

**Additional context**
The first time I encountered this problem was September 3. on September 2nd you released version 2.2.2 but I installed earlier versions and it still didn't work.

**Comment by punyflash** [comment]
Dublicate of #59. I tested inline mode and it works well, attaching script below. Again - your description is unclear. You are only telling that something is not working, but not providing code examples and full error trace. I'm not responsible for mistakes you make in your project.
```php
<?php

use WeStacks\TeleBot\Objects\Update;
use WeStacks\TeleBot\TeleBot;

require_once 'vendor/autoload.php';

$bot = new TeleBot([
    'token' => '<token>'
]);

$bot->addHandler(function (TeleBot $bot, Update $update, callable $next) {
    if (!isset($update->inline_query)) {
        return $next();
    }

    return $bot->answerInlineQuery([
        'inline_query_id' => $update->inline_query->id,
        'results' => [[
            'type' => 'article',
            'id' => 'google',
            'title' => 'Google',
            'url' => 'http://google.com/',
            'input_message_content' => [
                'message_text' => $update->inline_query->query
            ]
        ]]
    ]);
});

$last_offset = 0;
while (true) {
    $updates = $bot->getUpdates([
        'offset' => $last_offset + 1
    ]);
    foreach ($updates as $update) {
        $bot->handleUpdate($update);
        $last_offset = $update->update_id;
    }
}
```

**Comment by DyarWeb** [comment]
This is a [test](https://github.com/DyarWeb/testbot) and in the file [SearchMoviesInlineQuery.php](https://github.com/DyarWeb/testbot/blob/main/app/BotHandlers/SearchMoviesInlineQuery.php)
You can see is a very simple handler
But the update doesn't reach the handler and it exits in [Type.php:96](https://github.com/westacks/telebot/blob/master/src/Helpers/Type.php#L96) because $value_type is equal to NULL

**Comment by punyflash** [comment]
I've just cloned your project, and everything works as intended.
![image](https://user-images.githubusercontent.com/14828695/208089454-ce50065f-f65b-4dba-99db-1cda4799dc80.png)
![image](https://user-images.githubusercontent.com/14828695/208089605-07e66337-8a2a-4fff-beed-2c1846970fa4.png)

**Comment by DyarWeb** [comment]
I really don't understand that it works properly in long polling mode
![Screenshot from 2022-12-16 17-14-49](https://user-images.githubusercontent.com/67329708/208112395-038b3448-7d4a-4837-85e5-44e5c9019321.png)
![image](https://user-images.githubusercontent.com/67329708/208112661-e003df24-b822-4f95-83e8-a8a0946eb0e1.png)

But it gives an error in the webhook
![Screenshot from 2022-12-16 17-23-51](https://user-images.githubusercontent.com/67329708/208113477-fae7e5ec-a4e6-4ae6-a83b-9c6c6548986d.png)
![image](https://user-images.githubusercontent.com/67329708/208113768-afa649a8-5123-4621-b228-0dd53415e24e.png)

**Comment by punyflash** [comment]
I figured it out. It is actually a bug. There is a weird behavior in Telegram's API: when the incoming update is inline query, there is a field - `inline_query.offset`. [Documentation ](https://core.telegram.org/bots/api#inlinequery) says that this field is actually a string, however - when you receive updates using long polling, it's actually an empty string. But when they send a webhook request - they send `NULL`, that is not passing validation in our library. It's kind of weird, but I guess we can write some "crutches".

**Comment by punyflash** [comment]
Actually, by second though, it's not Telegram's API, but Laravel's middleware, that converts empty strings to `NULL` on every request. It's even easier to fix then

**Comment by punyflash** [comment]
For quick fix: enter `app/Http/Kernel.php` and remove `ConvertEmptyStringsToNull` middleware from your global middleware list. In the next update, I'll write the webhook route in a way to bypass Laravel's global middleware

```php
    protected $middleware = [
        // \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];
```

**Comment by DyarWeb** [comment]
ok thank you
