### ISSUE TITLE
[BUG] Declaration of Handler::write(array $record): void must be compatible with AbstractProcessingHandler::write(Monolog\LogRecord $record): void

### ISSUE THREAD

**Issue by mafftor** [westacks/telebot#81]
**Describe the bug**
Broken symfony logging bundle

**To Reproduce**
1. Install laravel 10
2. Install this bundle telebot
3. Setup new logging channel described in docs `laravel`
4. Specify default log_channel as newly created
5. Log something
6. perform request

**Expected behavior**
Message sent to the chat id

**Screenshots**
![image](https://github.com/westacks/telebot/assets/7810087/47ae9d76-edde-41aa-affc-bbc7499ddd71)

**Additional context**
Bundle v2.7.1

**Comment by mafftor** [comment]
To fix - change type hint of `$record` in `write` method

**Comment by mafftor** [comment]
I've changed in Handler.php following:

```php
use Monolog\LogRecord;
```

```php
public function write(LogRecord $record): void
```

```php
private function formatText(LogRecord $record): string
```

```php
return view('telebot::log', array_merge(['formatted' => $record->formatted], $record->toArray(), [
```

Here is entire updated class:
```php
<?php

namespace WeStacks\TeleBot\Laravel\Log;

use Monolog\Formatter\FormatterInterface;
use Monolog\Formatter\LineFormatter;
use Monolog\Handler\AbstractProcessingHandler;
use Monolog\LogRecord;
use Monolog\Logger;
use WeStacks\TeleBot\TeleBot;

class Handler extends AbstractProcessingHandler
{
    /**
     * Bot instance.
     *
     * @var TeleBot
     */
    protected $bot;

    /**
     * Chat id to send log message.
     *
     * @var string
     */
    protected $chat_id;

    /**
     * App name.
     *
     * @var string
     */
    protected $app;

    /**
     * App env.
     *
     * @var string
     */
    protected $env;

    public function __construct(array $config)
    {
        $level = Logger::toMonologLevel($config['level']);

        parent::__construct($level, true);

        // define variables for making Telegram request
        $this->bot = app('telebot')->bot($config['bot'] ?? null);
        $this->chat_id = $config['chat_id'];

        // define variables for text message
        $this->app = config('app.name');
        $this->env = config('app.env');
    }

    public function write(LogRecord $record): void
    {
        $textChunks = str_split($this->formatText($record), 4096);

        foreach ($textChunks as $textChunk) {
            $this->sendMessage($textChunk);
        }
    }

    /**
     * {@inheritDoc}
     */
    protected function getDefaultFormatter(): FormatterInterface
    {
        return new LineFormatter("%message% %context% %extra%\n");
    }

    private function formatText(LogRecord $record): string
    {
        return view('telebot::log', array_merge(['formatted' => $record->formatted], $record->toArray(), [
            'app' => $this->app,
            'env' => $this->env,
        ]))->render();
    }

    private function sendMessage(string $text): void
    {
        $this->bot->exceptions(false)->async(false)->sendMessage([
            'chat_id' => $this->chat_id,
            'parse_mode' => 'html',
            'text' => $text,
        ]);
    }
}
```

**Comment by mafftor** [comment]
Here is my logging config
```php
'telegram' => [
            'formatter' => Monolog\Formatter\LineFormatter::class,
            'driver'    => 'custom',
            'via'       => TelegramLogger::class,
            'level'     => 'debug',
            'bot'       => 'bot',
            'chat_id'   => env('TELEGRAM_LOG_CHAT_ID')
        ]
```

Idk if `formatter` line is necessary

**Comment by mafftor** [comment]
This is just a hotfix for my version, please do not copy&paste.
Save backward compatibility

**Comment by punyflash** [comment]
Hello, thanks a lot for your bug request. This seems to be changed in Monolog v3. Fixed in fa70e8c234af256ccb70de2ab0c1e127e8c24af1

**Comment by mafftor** [comment]
You're welcome! Nice bot! I've used it in my diploma project in university:)
Slava Ukraine! 🇺🇦

**Comment by mafftor** [comment]
Small notice about your change commit. You've written type hint for array and LogRecord object, but you do ->toArray() for object, but when array will be passed it would throw an error that it is not possible to call toArray method for array.
I'd write some method that would prepare data and you can check whether it is array or object and always return array for format method :)

**Comment by punyflash** [comment]
> Small notice about your change commit. You've written type hint for array and LogRecord object, but you do ->toArray() for object, but when array will be passed it would throw an error that it is not possible to call toArray method for array. I'd write some method that would prepare data and you can check whether it is array or object and always return array for format method :)

There is a check if passed record is an instance of `LogRecord`, so there will be no error
```php
if (is_a($record, LogRecord::class)) {
    $record = array_merge($record->toArray(), ['formatted' => $record->formatted]);
}
```
